# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'patent_download.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_patent_spider(object):
    def setupUi(self, patent_spider):
        patent_spider.setObjectName("patent_spider")
        patent_spider.resize(378, 400)
        self.centralwidget = QtWidgets.QWidget(patent_spider)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 371, 341))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.type_choose = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.type_choose.setMinimumSize(QtCore.QSize(210, 25))
        self.type_choose.setMaximumSize(QtCore.QSize(210, 25))
        self.type_choose.setObjectName("type_choose")
        self.type_choose.addItem("")
        self.type_choose.addItem("")
        self.type_choose.addItem("")
        self.gridLayout.addWidget(self.type_choose, 2, 1, 1, 2)
        self.download = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.download.setMinimumSize(QtCore.QSize(150, 50))
        self.download.setMaximumSize(QtCore.QSize(150, 50))
        self.download.setObjectName("download")
        self.gridLayout.addWidget(self.download, 7, 2, 1, 1)
        self.basicdata_save = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.basicdata_save.setMinimumSize(QtCore.QSize(150, 50))
        self.basicdata_save.setObjectName("basicdata_save")
        self.gridLayout.addWidget(self.basicdata_save, 7, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(30, 15))
        self.label_5.setMaximumSize(QtCore.QSize(150, 25))
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.path_road = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.path_road.setMaximumSize(QtCore.QSize(150, 28))
        self.path_road.setObjectName("path_road")
        self.gridLayout.addWidget(self.path_road, 0, 0, 1, 1)
        self.keyword = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.keyword.setMinimumSize(QtCore.QSize(210, 25))
        self.keyword.setMaximumSize(QtCore.QSize(210, 25))
        self.keyword.setObjectName("keyword")
        self.gridLayout.addWidget(self.keyword, 1, 1, 1, 2)
        self.num_decide = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.num_decide.setMinimumSize(QtCore.QSize(30, 25))
        self.num_decide.setMaximumSize(QtCore.QSize(50, 25))
        self.num_decide.setAlignment(QtCore.Qt.AlignCenter)
        self.num_decide.setObjectName("num_decide")
        self.gridLayout.addWidget(self.num_decide, 6, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setMaximumSize(QtCore.QSize(150, 25))
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setMaximumSize(QtCore.QSize(150, 25))
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(150, 25))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.route_show = QtWidgets.QLabel(self.gridLayoutWidget)
        self.route_show.setMinimumSize(QtCore.QSize(212, 30))
        self.route_show.setMaximumSize(QtCore.QSize(212, 30))
        self.route_show.setObjectName("route_show")
        self.gridLayout.addWidget(self.route_show, 0, 1, 1, 2)
        self.state = QtWidgets.QLabel(self.gridLayoutWidget)
        self.state.setMinimumSize(QtCore.QSize(369, 20))
        self.state.setMaximumSize(QtCore.QSize(369, 20))
        self.state.setAlignment(QtCore.Qt.AlignCenter)
        self.state.setObjectName("state")
        self.gridLayout.addWidget(self.state, 8, 0, 1, 3)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(15, 0))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 1, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar.setProperty("value", 100)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 9, 0, 1, 3)
        self.order_choose = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.order_choose.setMinimumSize(QtCore.QSize(210, 25))
        self.order_choose.setMaximumSize(QtCore.QSize(210, 25))
        self.order_choose.setObjectName("order_choose")
        self.order_choose.addItem("")
        self.order_choose.addItem("")
        self.order_choose.addItem("")
        self.order_choose.addItem("")
        self.gridLayout.addWidget(self.order_choose, 3, 1, 1, 2)
        self.research = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.research.setMinimumSize(QtCore.QSize(150, 40))
        self.research.setMaximumSize(QtCore.QSize(300, 40))
        self.research.setObjectName("research")
        self.gridLayout.addWidget(self.research, 4, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.gridLayoutWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout.addWidget(self.frame, 5, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(55, 40))
        self.label_7.setMaximumSize(QtCore.QSize(55, 40))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 1, 1, 1)
        patent_spider.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(patent_spider)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 378, 26))
        self.menubar.setObjectName("menubar")
        patent_spider.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(patent_spider)
        self.statusbar.setObjectName("statusbar")
        patent_spider.setStatusBar(self.statusbar)

        self.retranslateUi(patent_spider)
        QtCore.QMetaObject.connectSlotsByName(patent_spider)

    def retranslateUi(self, patent_spider):
        _translate = QtCore.QCoreApplication.translate
        patent_spider.setWindowTitle(_translate("patent_spider", "专利爬取"))
        self.type_choose.setItemText(0, _translate("patent_spider", "发明专利"))
        self.type_choose.setItemText(1, _translate("patent_spider", "实用新型专利"))
        self.type_choose.setItemText(2, _translate("patent_spider", "外观设计专利"))
        self.download.setText(_translate("patent_spider", "批量下载"))
        self.basicdata_save.setText(_translate("patent_spider", "整理简要资料"))
        self.label_5.setText(_translate("patent_spider", "篇数"))
        self.path_road.setText(_translate("patent_spider", "Path"))
        self.num_decide.setText(_translate("patent_spider", "19"))
        self.label_3.setText(_translate("patent_spider", "专利类型选择"))
        self.label_4.setText(_translate("patent_spider", "排序类型"))
        self.label_2.setText(_translate("patent_spider", "输入关键词"))
        self.route_show.setText(_translate("patent_spider", "D:\\data"))
        self.state.setText(_translate("patent_spider", "..."))
        self.label_6.setText(_translate("patent_spider", "1 ----"))
        self.order_choose.setItemText(0, _translate("patent_spider", "相关度"))
        self.order_choose.setItemText(1, _translate("patent_spider", "下载量"))
        self.order_choose.setItemText(2, _translate("patent_spider", "申请时间"))
        self.order_choose.setItemText(3, _translate("patent_spider", "公开时间"))
        self.research.setText(_translate("patent_spider", "搜索"))
        self.label.setText(_translate("patent_spider", "？篇"))
        self.label_7.setText(_translate("patent_spider", "共有"))


